name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  API_URL: https://sensortower.com/api/ios/featured/today/stories

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Set date
        run: echo "START_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Fetch data
        uses: githubocto/flat@v3
        env:
          COUNTRY: KR
        with:
          http_url: ${{env.API_URL}}?country=${{env.COUNTRY}}&start_date=${{env.START_DATE}}
          downloaded_filename: raw_data/${{env.COUNTRY}}/data.json
          postprocess: postprocess.js
